### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by Karonsbo** [jamesl1001/deviantART-Gallery-Plugin#1]
Hi!
I get the following error when I try to use this:
Failed to load resource: the server responded with a status of 404 (Not Found)
- ERROR - Original site javascript does not exist. This is a placeholder.  Url is 'https://www.w3schools.com/html/deviantART-gallery-plugin.min.js'. Time is 'Mon, 27 Feb 2017 14:08:20 UTC'.

How can this be solved?

**Comment by jamesl1001** [comment]
Hi,

I'm not sure why you are referencing the w3schools url.

Please download the source javascript file and host it within your own site files.
