### ISSUE TITLE
Error when trying to use plugin

### ISSUE THREAD

**Issue by Red2Blaze** [jamesl1001/deviantART-Gallery-Plugin#2]
Hey there, I am honeslty not much of a programer, so hope its not something simple I am just missing
I follow the setup steps and set it all up, but it dose not seem to show on the site
I get this error:
`https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20xml%20where%20url%3D%22https%3A//backend.deviantart.com/rss.xml%3Fq%3Dgallery%3Ared2blaze/45876137%22&_maxage=86400&format=json&callback=callback net::ERR_NAME_NOT_RESOLVED`

Am I doing something wrong? trying to put it here:
https://www.null2.space/

Any help will be great
I hope this is yet active.. it sounds awesome

**Comment by jamesl1001** [comment]
Thanks for bringing this to my attention!

The issue was that Yahoo deprecated their YQL API.

I have updated the repo and everything should now be working again.

Good luck with the site!
